In [1]:
import pandas as pd

Q1

In [2]:
arr = {"aman", "222",777,400.4}
print(arr)
arr = tuple(arr)
print(arr)

{400.4, 'aman', '222', 777}
(400.4, 'aman', '222', 777)


Q2

In [3]:
data = {"RollNo" : "cb.en.u4cse20232",
        "lastName" : "Koduru",
        "FirstName" : "Vivek",
        "dateofBirth" : "24/10/2002"}
print(data)

{'RollNo': 'cb.en.u4cse20232', 'lastName': 'Koduru', 'FirstName': 'Vivek', 'dateofBirth': '24/10/2002'}


In [4]:
import numpy as np

Q3

In [5]:
np.random.seed(100)
arr = np.random.randint(20,size = (2,3))
print(arr)

[[ 8  3  7]
 [15 16 10]]


In [6]:
from numpy import random

Q4

In [7]:
x = random.uniform(0.0,0.1)
print(x)

0.0004718856190972565


In [8]:
print(abs(-1234))

1234


Q5

In [9]:
x = random.randint(20,90)
print(x)

73


Q6

In [10]:
pop = [11,12,13,14,15]
np.random.shuffle(pop)
print(pop)
print(pop[random.randint(0,5)])
temp=[pop.pop(random.randint(0,5)),pop.pop(random.randint(0,4)),pop.pop(random.randint(0,3))]
print(temp)

[12, 11, 14, 15, 13]
11
[12, 11, 14]


Q7

In [11]:
f = open('text.txt','w')
f.write("The King is Dead, Long Live The King")
f.close()
f = open('text.txt','r')
for i in f:
  print(i,end=" ")
f.close()

The King is Dead, Long Live The King 

Q8

In [12]:
def func(x,y,w,k=6,z=None):
    if(z==None):
        return x+y
    elif(k==6):
        return x+y+k
    else:
        return x+y+w
print(func(2,3,4,5,6))
print(func(2,5,9))
print(func(2,6,4,7,10),"\n\n")

def func1(x):
    for i in range(0,6):
        while(x!=None):
            if(x<=10):
                print(x)
                x=x+1
                continue
            else:
                break
print(func1(1),"\n")
print(func1(6))

9
7
12 


1
2
3
4
5
6
7
8
9
10
None 

6
7
8
9
10
None


Q9

In [13]:
text = "The King is Dead, Long Live The King"
print(text)
print(text[0])
print(text[3:5])
print(text[3:])
words = text.split()
print(words)

The King is Dead, Long Live The King
T
 K
 King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


Q10

In [14]:
num = [1,4,5,8]
flo = [float(x) for x in num]
arr = np.array(flo)
arr
print(arr[0:2])

[1. 4.]


Q11

In [15]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


Q12

In [17]:
print(arr[1])
x = arr.astype(np.float64)
print(arr[0:2,1:])
print(len(arr))
length = sum(len(l) for l in arr)
print(length)

[4 5 6]
[[2 3]
 [5 6]]
2
6


Q13

In [18]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr3)
print(arr3.ndim)
arr4 = np.reshape(arr3,(5,2))
print(arr4)
print(arr4.ndim)
tran= arr4.transpose()
print(tran)

[ 1  2  3  4  5  6  7  8  9 10]
1
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


Q14

In [19]:
lis = [1,2,3]
print(lis)
arr5 = np.array(lis)
print(arr5)

[1, 2, 3]
[1 2 3]


Q15

In [20]:
arr6 = np.array([1,2,3])
arr6.fill(9)
print(arr6)

[9 9 9]


Q16

In [21]:
arr = np.array([[2,4,5]])
print(np.sum(arr))

11


Q17

In [22]:
arr = np.array([77,74,75])
val = 1
for i in arr:
  val*=i
print(val)

427350


Q18

In [23]:
arr = np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print(np.mean(arr))
print(np.var(arr))
print(np.max(arr))
print(np.min(arr))
print(np.median(arr))
print(np.std(arr))
print(np.argmin(arr))
print(np.argmax(arr))

12.461538461538462
367.32544378698225
56
1
2.0
19.165736192147232
1
12


Q19

In [24]:
arr = np.array([1,1,4,5,5,5,7])
q = {}
for i in arr:
  if i in q:
    q[i]+=1
  else:
    q[i]=1
arr1 = []
for i in q:
  if q[i]==1:
    arr1.append(i)
print("array : ",arr1)

array :  [4, 7]


Q20

In [25]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([0, 1, 1])
print(np.dot(arr1,arr2))

5


Q21

In [26]:
from numpy import linalg as LA
arr = np.array([[2,-12],[1,-5]])
w, v = LA.eig(arr)
print(w)
print(v)

[-1. -2.]
[[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]


Q22

In [28]:
arr = np.array([[11, 22, 11, 31], [25, 33, 31, 28]])
arr = arr.astype(np.float64)
print(np.corrcoef(arr))

[[1.         0.15997968]
 [0.15997968 1.        ]]
